theme: minima
title: UK OMOP Community Pages
description: Resources for the UK community engaged in mapping health data to OMOP
header_pages:
  - community.md
  - events.md
  - tools.md
  - governance.md
  - datasets.md
